---

- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /opt/wallpapers
    state: directory
    mode: '0755'

- name: Copy wallpapers to /opt/wallpapers
  become: true
  ansible.builtin.copy:
    src: "files/images"
    dest: /opt/wallpapers
    owner: root
    group: root
    mode: '0666'